---
title: Learning ordinal regression in R
author: Taylor Dunn
date: '2020-03-10'
slug: ordinal-regression
categories: []
tags: []
references:
- id: Randall1989
  title: The analysis of sensory data by generalised linear model.
  author:
  - family: Randall
    given: J
  container-title: Biometrical journal
  volume: 7
  page: 781-793
  type: article-journal
  issued:
    year: 1989
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p>AKA cumulative link models, ordered logit models, ordered probit models, proportional odds models.</p>
<p>I will explore three general frameworks:</p>
<ul>
<li>Frequentist maximum likelihood fixed effects models</li>
<li>Frequentist maximum likelihood mixed effects models</li>
<li>Bayesian mixed effects models</li>
</ul>
<div id="the-ordinal-package" class="section level1">
<h1>The <code>ordinal</code> package</h1>
<ul>
<li><a href="https://cran.r-project.org/web/packages/ordinal/vignettes/clmm2_tutorial.pdf"><code>ordinal</code> vignette</a></li>
<li><a href="https://r-forge.r-project.org/scm/viewvc.php/*checkout*/pkg/ordinal/inst/doc/primer.pdf?revision=66&amp;root=ordinal&amp;pathrev=69"><code>ordinal</code> primer</a></li>
</ul>
<p>Because</p>
<ul>
<li>It allows for various random effect structures</li>
<li>It has <a href="https://rdrr.io/cran/broom/man/ordinal_tidiers.html"><code>broom</code> tidy method</a></li>
</ul>
</div>
<div id="the-data" class="section level1">
<h1>The data</h1>
<p>Import the <code>wine</code> data set, adopted from <span class="citation">(Randall 1989)</span>:</p>
<pre class="r"><code>data(wine)
wine &lt;- as_tibble(wine)
glimpse(wine)</code></pre>
<pre><code>## Observations: 72
## Variables: 6
## $ response &lt;dbl&gt; 36, 48, 47, 67, 77, 60, 83, 90, 17, 22, 14, 50, 30, 51, 90...
## $ rating   &lt;ord&gt; 2, 3, 3, 4, 4, 4, 5, 5, 1, 2, 1, 3, 2, 3, 5, 4, 2, 3, 3, 2...
## $ temp     &lt;fct&gt; cold, cold, cold, cold, warm, warm, warm, warm, cold, cold...
## $ contact  &lt;fct&gt; no, no, yes, yes, no, no, yes, yes, no, no, yes, yes, no, ...
## $ bottle   &lt;fct&gt; 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4...
## $ judge    &lt;fct&gt; 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3...</code></pre>
<ul>
<li>Outcome:
<ul>
<li><code>response</code>: wine bitterness rating on a 0-100 scale</li>
<li><code>rating</code>: ordered factor with 5 levels (grouped version of <code>response</code>) with 1 = “least bitter” and 5 = “most bitter”</li>
</ul></li>
<li>Treatment factors:
<ul>
<li><code>temp</code>: temperature during wine production (cold and warm)</li>
<li><code>contact</code>: contact between juice and skins during wine production (no and yes)</li>
</ul></li>
<li>Random effects
<ul>
<li><code>bottle</code> with 8 levels</li>
<li><code>judge</code> with 9 levels</li>
</ul></li>
</ul>
<p>Relationship between <code>response</code> and <code>rating</code>:</p>
<pre class="r"><code>wine %&gt;%
  ggplot(aes(x = rating, y = response)) +
  geom_boxplot() +
  geom_jitter()</code></pre>
<p><img src="/post/2020-03-10-learning-ordinal-regression-in-r_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Note that there is no overlap between the levels.</p>
<p>There are 72 total observations with the following ratings distribution by treatment and random effects:</p>
<pre class="r"><code>wine %&gt;%
  select(temp, contact, bottle, judge, rating) %&gt;%
  spread(judge, rating) %&gt;%
  gt() %&gt;%
  tab_spanner(columns = vars(`1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`),
              label = &quot;judge&quot;)</code></pre>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#ikszmzaeoh .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
}

#ikszmzaeoh .gt_heading {
  background-color: #FFFFFF;
  border-bottom-color: #FFFFFF;
  border-left-style: hidden;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: hidden;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ikszmzaeoh .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ikszmzaeoh .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ikszmzaeoh .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ikszmzaeoh .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ikszmzaeoh .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ikszmzaeoh .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ikszmzaeoh .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ikszmzaeoh .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ikszmzaeoh .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ikszmzaeoh .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#ikszmzaeoh .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ikszmzaeoh .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ikszmzaeoh .gt_from_md > :first-child {
  margin-top: 0;
}

#ikszmzaeoh .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ikszmzaeoh .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ikszmzaeoh .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#ikszmzaeoh .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ikszmzaeoh .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#ikszmzaeoh .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ikszmzaeoh .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ikszmzaeoh .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ikszmzaeoh .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ikszmzaeoh .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#ikszmzaeoh .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ikszmzaeoh .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#ikszmzaeoh .gt_left {
  text-align: left;
}

#ikszmzaeoh .gt_center {
  text-align: center;
}

#ikszmzaeoh .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ikszmzaeoh .gt_font_normal {
  font-weight: normal;
}

#ikszmzaeoh .gt_font_bold {
  font-weight: bold;
}

#ikszmzaeoh .gt_font_italic {
  font-style: italic;
}

#ikszmzaeoh .gt_super {
  font-size: 65%;
}

#ikszmzaeoh .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="ikszmzaeoh" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">temp</th>
      <th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">contact</th>
      <th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">bottle</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="9">
        <span class="gt_column_spanner">judge</span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">1</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">2</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">3</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">4</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">5</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">6</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">7</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">8</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">9</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_center">cold</td>
      <td class="gt_row gt_center">no</td>
      <td class="gt_row gt_center">1</td>
      <td class="gt_row gt_center">2</td>
      <td class="gt_row gt_center">1</td>
      <td class="gt_row gt_center">2</td>
      <td class="gt_row gt_center">3</td>
      <td class="gt_row gt_center">2</td>
      <td class="gt_row gt_center">3</td>
      <td class="gt_row gt_center">1</td>
      <td class="gt_row gt_center">2</td>
      <td class="gt_row gt_center">1</td>
    </tr>
    <tr>
      <td class="gt_row gt_center gt_striped">cold</td>
      <td class="gt_row gt_center gt_striped">no</td>
      <td class="gt_row gt_center gt_striped">2</td>
      <td class="gt_row gt_center gt_striped">3</td>
      <td class="gt_row gt_center gt_striped">2</td>
      <td class="gt_row gt_center gt_striped">3</td>
      <td class="gt_row gt_center gt_striped">2</td>
      <td class="gt_row gt_center gt_striped">3</td>
      <td class="gt_row gt_center gt_striped">2</td>
      <td class="gt_row gt_center gt_striped">1</td>
      <td class="gt_row gt_center gt_striped">2</td>
      <td class="gt_row gt_center gt_striped">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_center">cold</td>
      <td class="gt_row gt_center">yes</td>
      <td class="gt_row gt_center">3</td>
      <td class="gt_row gt_center">3</td>
      <td class="gt_row gt_center">1</td>
      <td class="gt_row gt_center">3</td>
      <td class="gt_row gt_center">3</td>
      <td class="gt_row gt_center">4</td>
      <td class="gt_row gt_center">3</td>
      <td class="gt_row gt_center">2</td>
      <td class="gt_row gt_center">2</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_center gt_striped">cold</td>
      <td class="gt_row gt_center gt_striped">yes</td>
      <td class="gt_row gt_center gt_striped">4</td>
      <td class="gt_row gt_center gt_striped">4</td>
      <td class="gt_row gt_center gt_striped">3</td>
      <td class="gt_row gt_center gt_striped">2</td>
      <td class="gt_row gt_center gt_striped">2</td>
      <td class="gt_row gt_center gt_striped">3</td>
      <td class="gt_row gt_center gt_striped">2</td>
      <td class="gt_row gt_center gt_striped">2</td>
      <td class="gt_row gt_center gt_striped">3</td>
      <td class="gt_row gt_center gt_striped">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_center">warm</td>
      <td class="gt_row gt_center">no</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">4</td>
      <td class="gt_row gt_center">2</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">3</td>
      <td class="gt_row gt_center">3</td>
      <td class="gt_row gt_center">2</td>
      <td class="gt_row gt_center">2</td>
      <td class="gt_row gt_center">3</td>
      <td class="gt_row gt_center">3</td>
    </tr>
    <tr>
      <td class="gt_row gt_center gt_striped">warm</td>
      <td class="gt_row gt_center gt_striped">no</td>
      <td class="gt_row gt_center gt_striped">6</td>
      <td class="gt_row gt_center gt_striped">4</td>
      <td class="gt_row gt_center gt_striped">3</td>
      <td class="gt_row gt_center gt_striped">5</td>
      <td class="gt_row gt_center gt_striped">2</td>
      <td class="gt_row gt_center gt_striped">3</td>
      <td class="gt_row gt_center gt_striped">4</td>
      <td class="gt_row gt_center gt_striped">3</td>
      <td class="gt_row gt_center gt_striped">3</td>
      <td class="gt_row gt_center gt_striped">2</td>
    </tr>
    <tr>
      <td class="gt_row gt_center">warm</td>
      <td class="gt_row gt_center">yes</td>
      <td class="gt_row gt_center">7</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">4</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">3</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">2</td>
      <td class="gt_row gt_center">3</td>
      <td class="gt_row gt_center">4</td>
    </tr>
    <tr>
      <td class="gt_row gt_center gt_striped">warm</td>
      <td class="gt_row gt_center gt_striped">yes</td>
      <td class="gt_row gt_center gt_striped">8</td>
      <td class="gt_row gt_center gt_striped">5</td>
      <td class="gt_row gt_center gt_striped">4</td>
      <td class="gt_row gt_center gt_striped">4</td>
      <td class="gt_row gt_center gt_striped">3</td>
      <td class="gt_row gt_center gt_striped">3</td>
      <td class="gt_row gt_center gt_striped">4</td>
      <td class="gt_row gt_center gt_striped">3</td>
      <td class="gt_row gt_center gt_striped">4</td>
      <td class="gt_row gt_center gt_striped">4</td>
    </tr>
  </tbody>
  
  
</table></div>
<p>So each <code>bottle</code> had a particular <code>temp</code> and <code>contact</code> (2 bottles for each of the 4 combinations), and each <code>judge</code> rated each bottle.</p>
<p>Before modeling, can we see a clear effect of <code>temp</code> and <code>contact</code>?</p>
<pre class="r"><code>wine %&gt;%
  count(contact, rating, temp) %&gt;%
  mutate(temp = fct_rev(temp)) %&gt;%
  ggp(aes(x = contact, y = rating, color = temp)) +
  geom_point(aes(group = temp, size = n), position = position_dodge(1)) +
  cowplot::theme_minimal_hgrid() +
  facet_wrap(~contact, scales = &quot;free_x&quot;) +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank()
  ) +
  scale_size(breaks = c(1, 2, 4, 6, 8))</code></pre>
<p><img src="/post/2020-03-10-learning-ordinal-regression-in-r_files/figure-html/unnamed-chunk-4-1.png" width="384" /></p>
<p>At a glance, it looks like the <code>temp</code> = warm and <code>contact</code> = yes is associated with higher <code>rating</code>s.</p>
</div>
<div id="the-cumulative-link-model" class="section level1">
<h1>The cumulative link model</h1>
<div id="theory" class="section level2">
<h2>Theory</h2>
<p>The ordinal response <span class="math inline">\(y_i\)</span> falls into response category <span class="math inline">\(j\)</span> (out of <span class="math inline">\(J\)</span> total) with proability <span class="math inline">\(\pi_{ij}\)</span>.
The cumulative probabilities are defined:</p>
<p><span class="math display">\[
P(y_i \leq j) = \pi_{i1} + \dots + \pi_{ij}.
\]</span></p>
<p>As an oversimplification, suppose that each probability <span class="math inline">\(\pi_{ij}\)</span> is equal to the proportion of that response in the <code>wine</code> data.
Then the cumulative “probability” can be visualized:</p>
<pre class="r"><code>wine_prop &lt;- wine %&gt;%
  count(rating) %&gt;%
  mutate(p = n / sum(n),
         cumsum_p = cumsum(p))
(
ggp(wine_prop, aes(x = rating, y = p)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent, expand = c(0, 0)) +
  labs(x = &quot;j&quot;, y = &quot;proportion&quot;) +
  cowplot::theme_minimal_hgrid()
) +
  (
    ggp(wine_prop, aes(x = as.integer(rating), y = cumsum_p)) +
      geom_point() +
      geom_line() +
      labs(x = &quot;j&quot;, y = &quot;cumulative proportion&quot;) +
      cowplot::theme_minimal_hgrid()
  ) +
  (
    ggp(wine_prop,
        aes(x = as.integer(rating), y = log(cumsum_p) - log(1 - cumsum_p))) +
      geom_point() +
      geom_line() +
      labs(x = &quot;j&quot;, y = &quot;logit(cumulative proportion)&quot;) +
      cowplot::theme_minimal_hgrid()
  )</code></pre>
<p><img src="/post/2020-03-10-learning-ordinal-regression-in-r_files/figure-html/unnamed-chunk-5-1.png" width="960" /></p>
<p>We will explore other links, but first the most common, the logit link, which is depicted in the right-most panel of the above figure:</p>
<p><span class="math display">\[
\text{logit} (P(y_i \leq j) = \log \frac{P(y_i \leq j)}{1 - P(y_i \leq j)}
\]</span></p>
<p>Note that the above function is defined for all but the last category, because <span class="math inline">\(1 - P(Y_i \leq j) = 1 - 1 = 0\)</span>.</p>
<p>For the <code>wine</code> data, where we have <span class="math inline">\(J\)</span> = 5 rating categories, we will build up to the following mixed effects model:</p>
<p><span class="math display">\[
\begin{align}
\text{logit}(p(y_i \leq j)) &amp;= \theta_j - \beta_1 \text{temp}_i - \beta_2 \text{contact}_i - u( \text{judge}_i) \\
i &amp;= 1, \dots n \; \; \; \; \; \; j = 1, \dots, J - 1
\end{align}
\]</span></p>
<p>where <span class="math inline">\(\theta_j\)</span> is called the threshold parameter, or cutpoint, of category <span class="math inline">\(j\)</span>, which can also be thought of as <span class="math inline">\(J-1\)</span> = 4 intercepts.
Note that the fixed effect parameters <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span> are independent of <span class="math inline">\(j\)</span>, so each <span class="math inline">\(\beta\)</span> has the same effect for each of the <span class="math inline">\(J-1\)</span> cumulative logits.
The judge effects, which are also independent of <span class="math inline">\(j\)</span>, are assumed normal: <span class="math inline">\(u(\text{judge}_i) \sim N(0, \sigma_u^2)\)</span>.
We are using the logit link because it is the most popular for this kind of model (and the one I am familiar with), but there are other options we will briefly explore later.</p>
<p>The subtraction of terms in the above model is new to me.
The main reason seems to be a choice of familiar interpretation: the larger the value of any independent term <span class="math inline">\(\beta x\)</span>, the smaller the thresholds <span class="math inline">\(\theta_j\)</span>, and therefore a larger probability of the a response falling into a category at the upper end of the scale.
This way, <span class="math inline">\(\beta\)</span> has the same <em>direction</em> of effect as in ordinary linear regression.</p>
<p>We are essentially modeling a “chain” of logistic regressions where the binary response is “less than or equal to a certain level” vs “greater than that level”.
In this case, with <span class="math inline">\(J\)</span> = 5, the thresholds <span class="math inline">\(\theta_j\)</span> are capturing the adjusted log-odds of observing:</p>
<ul>
<li><span class="math inline">\(j\)</span> = 1: log-odds of <code>rating</code> = 1 vs. 2-5</li>
<li><span class="math inline">\(j\)</span> = 2: log-odds of <code>rating</code> = 1-2 vs. 3-5</li>
<li><span class="math inline">\(j\)</span> = 3: log-odds of <code>rating</code> = 1-3 vs. 4-5</li>
<li><span class="math inline">\(j\)</span> = 4: log-odds of <code>rating</code> = 1-4 vs. 5</li>
</ul>
</div>
<div id="fitting" class="section level2">
<h2>Fitting</h2>
<p>Now with a surface-level understanding of what is being modeled, we will fit the data using <code>ordinal::clm</code> (cumulative link models) and <code>ordinal::clmm</code> (cumulative link mixed models), and logit links.</p>
<div id="fixed-effects-model" class="section level3">
<h3>Fixed effects model</h3>
<p>First, fit a simple model, by maximum likelihood, with <code>contact</code> as the sole predictor:</p>
<p><span class="math display">\[
\text{logit}(p(y_i \leq j)) = \theta_j - \beta_2 \text{contact}_i
\]</span></p>
<pre class="r"><code>clm_rating_contact &lt;-
  clm(
    rating ~ contact,
    data = wine, link = &quot;logit&quot;
  )
summary(clm_rating_contact)</code></pre>
<pre><code>## formula: rating ~ contact
## data:    wine
## 
##  link  threshold nobs logLik AIC    niter max.grad cond.H 
##  logit flexible  72   -99.96 209.91 5(0)  1.67e-07 1.7e+01
## 
## Coefficients:
##            Estimate Std. Error z value Pr(&gt;|z|)   
## contactyes   1.2070     0.4499   2.683   0.0073 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Threshold coefficients:
##     Estimate Std. Error z value
## 1|2 -2.13933    0.48981  -4.368
## 2|3  0.04257    0.32063   0.133
## 3|4  1.71449    0.38637   4.437
## 4|5  2.97875    0.50207   5.933</code></pre>
<p>The model gives us <span class="math inline">\(K - 1 = 4\)</span> threshold coefficients, as expected.
The <span class="math inline">\(\beta_2\)</span> coefficient estimate was statistically significant (by a Wald test), and tells us that <code>contact</code> = yes <em>decreases</em> the thresholds <span class="math inline">\(\theta_j\)</span> by <span class="math inline">\(\beta_2\)</span> = 1.21 (because of the subtraction of model terms), and therefore is associated with <em>higher</em> <code>rating</code>s.</p>
<p>The condition number of the Hessian for this model is 16.98.
The primer says that larger values (like &gt; <code>1e4</code>) might indicate that the model is ill defined.</p>
<p>It is nicely illustrative to compare this model to 4 separate logistic regressions with a dichomtized response:</p>
<p><span class="math display">\[
\begin{align}
\text{logit} (p(y_i \leq 1)) = \theta_1 + \beta_2 \text{contact_i} \\
\text{logit} (p(y_i \leq 2)) = \theta_2 + \beta_2 \text{contact_i} \\
\text{logit} (p(y_i \leq 3)) = \theta_3 + \beta_2 \text{contact_i} \\
\text{logit} (p(y_i \leq 4)) = \theta_4 + \beta_2 \text{contact_i} \\
\end{align}
\]</span></p>
<pre class="r"><code>wine %&gt;%
  crossing(j = 1:4) %&gt;%
  # Create a binary (0 or 1) to indicate where rating &lt;= j
  mutate(rating_leq_j = as.numeric(rating) &lt;= j) %&gt;%
  group_by(j) %&gt;%
  nest() %&gt;%
  ungroup() %&gt;%
  mutate(
    mod = map(
      data,
      ~glm(rating_leq_j ~ 1 + contact,
           data = ., family = binomial(link = &quot;logit&quot;))
    ),
    mod_tidy = map(mod, tidy)
  ) %&gt;%
  unnest(mod_tidy) %&gt;%
  transmute(
    j, term,
    estimate_se = str_c(round(estimate, 2), &quot; (&quot;, round(std.error, 2), &quot;)&quot;)
  ) %&gt;%
  spread(term, estimate_se) %&gt;%
  left_join(
    tidy(clm_rating_contact) %&gt;%
      transmute(
        j = as.integer(substr(term, 1, 1)),
        term = if_else(!is.na(j), &quot;theta_j&quot;, term),
        estimate_se = str_c(round(estimate, 2), &quot; (&quot;, round(std.error, 2), &quot;)&quot;)
      ) %&gt;%
      mutate(j = replace_na(j, 1)) %&gt;%
      spread(term, estimate_se),
    by = &quot;j&quot;
  ) %&gt;%
  ungroup() %&gt;%
  gt() %&gt;%
  tab_spanner(label = &quot;Logistic regression&quot;,
              columns = vars(`(Intercept)`, contactyes.x)) %&gt;%
  tab_spanner(label = &quot;CLM&quot;,
              columns = vars(theta_j, contactyes.y)) %&gt;%
  fmt_missing(columns = everything(), missing_text = &quot;&quot;)</code></pre>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#nzyvfdbaas .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
}

#nzyvfdbaas .gt_heading {
  background-color: #FFFFFF;
  border-bottom-color: #FFFFFF;
  border-left-style: hidden;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: hidden;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nzyvfdbaas .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#nzyvfdbaas .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#nzyvfdbaas .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nzyvfdbaas .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nzyvfdbaas .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#nzyvfdbaas .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#nzyvfdbaas .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#nzyvfdbaas .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#nzyvfdbaas .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#nzyvfdbaas .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#nzyvfdbaas .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#nzyvfdbaas .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#nzyvfdbaas .gt_from_md > :first-child {
  margin-top: 0;
}

#nzyvfdbaas .gt_from_md > :last-child {
  margin-bottom: 0;
}

#nzyvfdbaas .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#nzyvfdbaas .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#nzyvfdbaas .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nzyvfdbaas .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#nzyvfdbaas .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nzyvfdbaas .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#nzyvfdbaas .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nzyvfdbaas .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nzyvfdbaas .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#nzyvfdbaas .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nzyvfdbaas .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#nzyvfdbaas .gt_left {
  text-align: left;
}

#nzyvfdbaas .gt_center {
  text-align: center;
}

#nzyvfdbaas .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#nzyvfdbaas .gt_font_normal {
  font-weight: normal;
}

#nzyvfdbaas .gt_font_bold {
  font-weight: bold;
}

#nzyvfdbaas .gt_font_italic {
  font-style: italic;
}

#nzyvfdbaas .gt_super {
  font-size: 65%;
}

#nzyvfdbaas .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="nzyvfdbaas" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">j</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2">
        <span class="gt_column_spanner">Logistic regression</span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2">
        <span class="gt_column_spanner">CLM</span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">(Intercept)</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">contactyes.x</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">theta_j</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">contactyes.y</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_right">1</td>
      <td class="gt_row gt_left">-2.08 (0.53)</td>
      <td class="gt_row gt_left">-1.48 (1.14)</td>
      <td class="gt_row gt_left">-2.14 (0.49)</td>
      <td class="gt_row gt_left">1.21 (0.45)</td>
    </tr>
    <tr>
      <td class="gt_row gt_right gt_striped">2</td>
      <td class="gt_row gt_left gt_striped">0 (0.33)</td>
      <td class="gt_row gt_left gt_striped">-1.1 (0.51)</td>
      <td class="gt_row gt_left gt_striped">0.04 (0.32)</td>
      <td class="gt_row gt_left gt_striped"></td>
    </tr>
    <tr>
      <td class="gt_row gt_right">3</td>
      <td class="gt_row gt_left">1.82 (0.48)</td>
      <td class="gt_row gt_left">-1.37 (0.59)</td>
      <td class="gt_row gt_left">1.71 (0.39)</td>
      <td class="gt_row gt_left"></td>
    </tr>
    <tr>
      <td class="gt_row gt_right gt_striped">4</td>
      <td class="gt_row gt_left gt_striped">2.83 (0.73)</td>
      <td class="gt_row gt_left gt_striped">-1.01 (0.87)</td>
      <td class="gt_row gt_left gt_striped">2.98 (0.5)</td>
      <td class="gt_row gt_left gt_striped"></td>
    </tr>
  </tbody>
  
  
</table></div>
<p>The intercepts from the ordinary logistic regression correspond closely to the threshold parameters <span class="math inline">\(\theta_j\)</span> from the cumulative link model.
In the fixed effect of <code>contact</code> (<span class="math inline">\(\beta_2\)</span>), first note the sign difference, and second notice that the estimate from CLM is about the average of the 4 estimates from logistic regression.
The advantage of the CLM is seen in the small standard error in the <span class="math inline">\(\beta_2\)</span> estimate.</p>
<p>To quote the primer:</p>
<blockquote>
<p>The cumulative logit model can be seen as the model that combines these four ordinary logistic regression models into a single model and therefore makes better use of the information in the data.</p>
</blockquote>
<p>For the second model, we add the <span class="math inline">\(\beta_1 \text{temp}_i\)</span> term:</p>
<p><span class="math display">\[
\text{logit}(p(y_i \leq j)) = \theta_j - \beta_1 \text{temp}_i - \beta_2 \text{contact}_i
\]</span></p>
<pre class="r"><code>clm_rating_contact_temp &lt;-
  clm(
    rating ~ contact + temp,
    data = wine, link = &quot;logit&quot;
  )
summary(clm_rating_contact_temp)</code></pre>
<pre><code>## formula: rating ~ contact + temp
## data:    wine
## 
##  link  threshold nobs logLik AIC    niter max.grad cond.H 
##  logit flexible  72   -86.49 184.98 6(0)  4.01e-12 2.7e+01
## 
## Coefficients:
##            Estimate Std. Error z value Pr(&gt;|z|)    
## contactyes   1.5278     0.4766   3.205  0.00135 ** 
## tempwarm     2.5031     0.5287   4.735 2.19e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Threshold coefficients:
##     Estimate Std. Error z value
## 1|2  -1.3444     0.5171  -2.600
## 2|3   1.2508     0.4379   2.857
## 3|4   3.4669     0.5978   5.800
## 4|5   5.0064     0.7309   6.850</code></pre>
<p>Both fixed effects (<code>contact</code> = yes and <code>temp</code> = warm) are strongly associated with higher probability of higher ratings.
The <code>summary()</code> function provides p values from Wald tests, but more accurate likelihood ratio tests can be done via the <code>drop1()</code> function, which evaluates each fixed effect while controlling the other:</p>
<pre class="r"><code>drop1(clm_rating_contact_temp, test = &quot;Chisq&quot;)</code></pre>
<pre><code>## Single term deletions
## 
## Model:
## rating ~ contact + temp
##         Df    AIC    LRT  Pr(&gt;Chi)    
## &lt;none&gt;     184.98                     
## contact  1 194.03 11.043 0.0008902 ***
## temp     1 209.91 26.928 2.112e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Or the reverse via the <code>add1()</code> function, which evaluates each fixed effect while ignoring the other:</p>
<pre class="r"><code># Fit the null model first
clm_rating_null &lt;-
  clm(
    rating ~ 1,
    data = wine, link = &quot;logit&quot;
  )
add1(clm_rating_null, scope = ~ contact + temp, test = &quot;Chisq&quot;)</code></pre>
<pre><code>## Single term additions
## 
## Model:
## rating ~ 1
##         Df    AIC     LRT  Pr(&gt;Chi)    
## &lt;none&gt;     215.44                      
## contact  1 209.91  7.5263   0.00608 ** 
## temp     1 194.03 23.4113 1.308e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Symmetric Wald confidence intervals can be extracted with <code>confint()</code> or with <code>broom::tidy()</code>:</p>
<pre class="r"><code>tidy(clm_rating_contact_temp, conf.int = T, conf.type = &quot;Wald&quot;) %&gt;%
  ggp(aes(y = term, x = estimate)) +
  geom_point() +
  geom_linerange(aes(xmin = conf.low, xmax = conf.high))</code></pre>
<p><img src="/post/2020-03-10-learning-ordinal-regression-in-r_files/figure-html/unnamed-chunk-11-1.png" width="480" /></p>
<p>In these types of analyses, we are often interested in the odds ratios.
For the two categorical fixed effects, which have two levels each, the odds ratios <span class="math inline">\(y \leq j\)</span> comparing the two levels are:</p>
<p><span class="math display">\[
\begin{align}
\text{OR} &amp;= \frac{\gamma_j (\text{temp} = \text{warm})}{\gamma_j (\text{temp} = \text{cold})} = \frac{\exp(\theta_j - \beta_1 - \beta_2 \text{contact})}{\exp (\theta_j - 0 - \beta_2 \text{contact}}) = \exp(\beta_1) \\
\text{OR} &amp;= \frac{\gamma_j (\text{contact} = \text{yes})}{\gamma_j (\text{contact} = \text{no})} = \frac{\exp(\theta_j - \beta_1 \text{temp} - \beta_2 )}{\exp (\theta_j - \beta_1 \text{temp} - 0)}) = \exp(\beta_2)
\end{align}
\]</span></p>
<p>where we have introducted the shorthand <span class="math inline">\(\gamma_j = \text{logit} (p(y \leq j))\)</span>.
Compute those odds ratios, and their corresponding Wald 95% CIs:</p>
<pre class="r"><code>tidy(clm_rating_contact_temp, conf.int = T, conf.type = &quot;Wald&quot;) %&gt;%
  transmute(
    term,
    across(c(estimate, conf.low, conf.high), exp)
  ) %&gt;%
  gt() %&gt;%
  fmt_number(vars(estimate, conf.low, conf.high), decimals = 2)</code></pre>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#hrgyrskxrd .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
}

#hrgyrskxrd .gt_heading {
  background-color: #FFFFFF;
  border-bottom-color: #FFFFFF;
  border-left-style: hidden;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: hidden;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hrgyrskxrd .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hrgyrskxrd .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hrgyrskxrd .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hrgyrskxrd .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hrgyrskxrd .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hrgyrskxrd .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hrgyrskxrd .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hrgyrskxrd .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hrgyrskxrd .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hrgyrskxrd .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#hrgyrskxrd .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hrgyrskxrd .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hrgyrskxrd .gt_from_md > :first-child {
  margin-top: 0;
}

#hrgyrskxrd .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hrgyrskxrd .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hrgyrskxrd .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#hrgyrskxrd .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hrgyrskxrd .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#hrgyrskxrd .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hrgyrskxrd .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hrgyrskxrd .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hrgyrskxrd .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hrgyrskxrd .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#hrgyrskxrd .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hrgyrskxrd .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#hrgyrskxrd .gt_left {
  text-align: left;
}

#hrgyrskxrd .gt_center {
  text-align: center;
}

#hrgyrskxrd .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hrgyrskxrd .gt_font_normal {
  font-weight: normal;
}

#hrgyrskxrd .gt_font_bold {
  font-weight: bold;
}

#hrgyrskxrd .gt_font_italic {
  font-style: italic;
}

#hrgyrskxrd .gt_super {
  font-size: 65%;
}

#hrgyrskxrd .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="hrgyrskxrd" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">term</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">estimate</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">conf.low</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">conf.high</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">1|2</td>
      <td class="gt_row gt_right">0.26</td>
      <td class="gt_row gt_right">0.09</td>
      <td class="gt_row gt_right">0.72</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">2|3</td>
      <td class="gt_row gt_right gt_striped">3.49</td>
      <td class="gt_row gt_right gt_striped">1.48</td>
      <td class="gt_row gt_right gt_striped">8.24</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">3|4</td>
      <td class="gt_row gt_right">32.04</td>
      <td class="gt_row gt_right">9.93</td>
      <td class="gt_row gt_right">103.39</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">4|5</td>
      <td class="gt_row gt_right gt_striped">149.37</td>
      <td class="gt_row gt_right gt_striped">35.65</td>
      <td class="gt_row gt_right gt_striped">625.75</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">contactyes</td>
      <td class="gt_row gt_right">4.61</td>
      <td class="gt_row gt_right">1.81</td>
      <td class="gt_row gt_right">11.73</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">tempwarm</td>
      <td class="gt_row gt_right gt_striped">12.22</td>
      <td class="gt_row gt_right gt_striped">4.34</td>
      <td class="gt_row gt_right gt_striped">34.44</td>
    </tr>
  </tbody>
  
  
</table></div>
<p>One last thing to check: does the model support an interaction between <span class="math inline">\(\text{temp}_i\)</span> and <span class="math inline">\(\text{contact}_i\)</span>?</p>
<p><span class="math display">\[
\text{logit}(p(y_i \leq j)) = \theta_j - \beta_1 \text{temp}_i - \beta_2 \text{contact}_i - \beta_3 \text{temp}_i \text{contact}_i
\]</span></p>
<pre class="r"><code>clm_rating_contact_temp_inter &lt;-
  clm(
    rating ~ contact * temp,
    data = wine, link = &quot;logit&quot;
  )
#drop1(clm_rating_contact_temp_inter, test = &quot;Chisq&quot;) # this accomplishes the same thing as anova()
anova(clm_rating_contact_temp, clm_rating_contact_temp_inter)</code></pre>
<pre><code>## Likelihood ratio tests of cumulative link models:
##  
##                               formula:                link: threshold:
## clm_rating_contact_temp       rating ~ contact + temp logit flexible  
## clm_rating_contact_temp_inter rating ~ contact * temp logit flexible  
## 
##                               no.par    AIC  logLik LR.stat df Pr(&gt;Chisq)
## clm_rating_contact_temp            6 184.98 -86.492                      
## clm_rating_contact_temp_inter      7 186.83 -86.416  0.1514  1     0.6972</code></pre>
<p>The interaction term <code>contact:temp</code> is not supported by the data.</p>
<div id="comparison-to-linear-model" class="section level4">
<h4>Comparison to linear model</h4>
<p>Consider the following linear model which treats <code>rating</code> as continuous:</p>
<p><span class="math display">\[
y_i = \alpha + \beta_1 \text{temp}_i + \beta_2 \text{contact}_i + \epsilon_i
\]</span></p>
<p>where <span class="math inline">\(\epsilon_i \sim N(0, \sigma_{\epsilon}^2)\)</span>.</p>
<pre class="r"><code>lm_rating_contact_temp &lt;-
  lm(as.numeric(rating) ~ contact + temp, data = wine)</code></pre>
<p>To compare this to a CLM, we must use the probit link:</p>
<pre class="r"><code>clm_rating_contact_temp_probit &lt;-
  clm(
    rating ~ contact + temp,
    data = wine, link = &quot;probit&quot;
  )

tidy(clm_rating_contact_temp_probit) %&gt;%
  filter(coefficient_type == &quot;beta&quot;) %&gt;%
  mutate(model = &quot;CLM&quot;) %&gt;%
  select(-coefficient_type) %&gt;%
  bind_rows(
    tidy(lm_rating_contact_temp) %&gt;%
      filter(term != &quot;(Intercept)&quot;) %&gt;%
      # Not sure why we need to divide by the residual SE here
      mutate(estimate = estimate / summary(lm_rating_contact_temp)$sigma,
             model = &quot;LM&quot;)
  ) %&gt;%
  group_by(model) %&gt;%
  gt() %&gt;%
  fmt_number(vars(estimate, std.error, statistic), decimals = 2) %&gt;%
  fmt(vars(p.value), fns = scales::pvalue)</code></pre>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#rjsmrtizdg .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
}

#rjsmrtizdg .gt_heading {
  background-color: #FFFFFF;
  border-bottom-color: #FFFFFF;
  border-left-style: hidden;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: hidden;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rjsmrtizdg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#rjsmrtizdg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#rjsmrtizdg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rjsmrtizdg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rjsmrtizdg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#rjsmrtizdg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#rjsmrtizdg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#rjsmrtizdg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#rjsmrtizdg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#rjsmrtizdg .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#rjsmrtizdg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#rjsmrtizdg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#rjsmrtizdg .gt_from_md > :first-child {
  margin-top: 0;
}

#rjsmrtizdg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#rjsmrtizdg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#rjsmrtizdg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#rjsmrtizdg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rjsmrtizdg .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#rjsmrtizdg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rjsmrtizdg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#rjsmrtizdg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rjsmrtizdg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rjsmrtizdg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#rjsmrtizdg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rjsmrtizdg .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#rjsmrtizdg .gt_left {
  text-align: left;
}

#rjsmrtizdg .gt_center {
  text-align: center;
}

#rjsmrtizdg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#rjsmrtizdg .gt_font_normal {
  font-weight: normal;
}

#rjsmrtizdg .gt_font_bold {
  font-weight: bold;
}

#rjsmrtizdg .gt_font_italic {
  font-style: italic;
}

#rjsmrtizdg .gt_super {
  font-size: 65%;
}

#rjsmrtizdg .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="rjsmrtizdg" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">term</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">estimate</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">std.error</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">statistic</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">p.value</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <td colspan="5" class="gt_group_heading">CLM</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">contactyes</td>
      <td class="gt_row gt_right">0.87</td>
      <td class="gt_row gt_right">0.27</td>
      <td class="gt_row gt_right">3.25</td>
      <td class="gt_row gt_right">0.001</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">tempwarm</td>
      <td class="gt_row gt_right gt_striped">1.50</td>
      <td class="gt_row gt_right gt_striped">0.29</td>
      <td class="gt_row gt_right gt_striped">5.14</td>
      <td class="gt_row gt_right gt_striped"><0.001</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="5" class="gt_group_heading">LM</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">contactyes</td>
      <td class="gt_row gt_right">0.79</td>
      <td class="gt_row gt_right">0.20</td>
      <td class="gt_row gt_right">3.36</td>
      <td class="gt_row gt_right">0.001</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">tempwarm</td>
      <td class="gt_row gt_right gt_striped">1.38</td>
      <td class="gt_row gt_right gt_striped">0.20</td>
      <td class="gt_row gt_right gt_striped">5.87</td>
      <td class="gt_row gt_right gt_striped"><0.001</td>
    </tr>
  </tbody>
  
  
</table></div>
<p>The relative estimates from the linear model are lower than those from the CLM (probit link), indicating that the assumptions of the linear model are not met.
In particular, the distance between thresholds is not equidistant:</p>
<pre class="r"><code>diff(coef(clm_rating_contact_temp_probit)[1:4]) %&gt;% round(2)</code></pre>
<pre><code>##  2|3  3|4  4|5 
## 1.51 1.31 0.90</code></pre>
</div>
</div>
<div id="mixed-effects-model" class="section level3">
<h3>Mixed effects model</h3>
<p>Now that we have explored ordinal regression with just fixed effects, we will fit the following random effects model:</p>
<p><span class="math display">\[
\begin{align}
\text{logit}(p(y_i \leq j)) &amp;= \theta_j - \beta_1 \text{temp}_i - \beta_2 \text{contact}_i - u( \text{judge}_i) \\
i &amp;= 1, \dots n \; \; \; \; \; \; j = 1, \dots, J - 1
\end{align}
\]</span>
where the judge effects are independent of <span class="math inline">\(j\)</span>, and assumed normal: <span class="math inline">\(u(\text{judge}_i) \sim N(0, \sigma_u^2)\)</span>.</p>
<p>Each judge has 8 <code>rating</code>s each (two per combination of <code>temp</code> and <code>contact</code>).
See if we can spot the <code>judge</code> variance:</p>
<pre class="r"><code>wine %&gt;%
  count(judge, rating) %&gt;%
  ggplot(aes(x = judge, y = rating)) +
  geom_tile(aes(fill = n)) +
  geom_text(aes(label = n), color = &quot;white&quot;) +
  cowplot::theme_half_open() +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) +
  theme(legend.position = &quot;none&quot;) +
  scale_fill_viridis_c() +
  labs(title = &quot;Number of ratings by judge&quot;)</code></pre>
<p><img src="/post/2020-03-10-learning-ordinal-regression-in-r_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>There is definitly some judge-specific variability in the perception of bitterness in wine.
<code>judge</code> 5, for instance, doesn’t stray far from <code>rating</code> = 3, while <code>judge</code> 7 didn’t consider any of the wines particularly bitter.</p>
<p>Fit the model with <code>ordinal::clmm</code> and logit link:</p>
<pre class="r"><code>clmm_rating_contact_temp &lt;-
  clmm(
    rating ~ temp + contact + (1|judge),
    data = wine, link = &quot;logit&quot;
  )
# This is an older function, which we need to run stats::profile later
clmm2_rating_contact_temp &lt;-
  clmm2(
    rating ~ temp + contact, random = judge,
    data = wine, link = &quot;logistic&quot;
  )
summary(clmm_rating_contact_temp)</code></pre>
<pre><code>## Cumulative Link Mixed Model fitted with the Laplace approximation
## 
## formula: rating ~ temp + contact + (1 | judge)
## data:    wine
## 
##  link  threshold nobs logLik AIC    niter    max.grad cond.H 
##  logit flexible  72   -81.57 177.13 332(999) 1.03e-05 2.8e+01
## 
## Random effects:
##  Groups Name        Variance Std.Dev.
##  judge  (Intercept) 1.279    1.131   
## Number of groups:  judge 9 
## 
## Coefficients:
##            Estimate Std. Error z value Pr(&gt;|z|)    
## tempwarm     3.0630     0.5954   5.145 2.68e-07 ***
## contactyes   1.8349     0.5125   3.580 0.000344 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Threshold coefficients:
##     Estimate Std. Error z value
## 1|2  -1.6237     0.6824  -2.379
## 2|3   1.5134     0.6038   2.507
## 3|4   4.2285     0.8090   5.227
## 4|5   6.0888     0.9725   6.261</code></pre>
<p>Compare model coefficients:</p>
<pre class="r"><code>tidy(clm_rating_contact_temp) %&gt;%
  select(-coefficient_type) %&gt;%
  mutate(model = &quot;CLM&quot;) %&gt;%
  bind_rows(
    tidy(clmm_rating_contact_temp) %&gt;%
      select(-coefficient_type) %&gt;%
      mutate(model = &quot;CLMM&quot;)
  ) %&gt;%
  group_by(model) %&gt;%
  gt() %&gt;%
  fmt_number(vars(estimate, std.error, statistic), decimals = 2) %&gt;%
  fmt(vars(p.value), fns = scales::pvalue)</code></pre>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#qcjtbyhczc .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
}

#qcjtbyhczc .gt_heading {
  background-color: #FFFFFF;
  border-bottom-color: #FFFFFF;
  border-left-style: hidden;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: hidden;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qcjtbyhczc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#qcjtbyhczc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#qcjtbyhczc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qcjtbyhczc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qcjtbyhczc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#qcjtbyhczc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#qcjtbyhczc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#qcjtbyhczc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#qcjtbyhczc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#qcjtbyhczc .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#qcjtbyhczc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#qcjtbyhczc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#qcjtbyhczc .gt_from_md > :first-child {
  margin-top: 0;
}

#qcjtbyhczc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#qcjtbyhczc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#qcjtbyhczc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#qcjtbyhczc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qcjtbyhczc .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#qcjtbyhczc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qcjtbyhczc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#qcjtbyhczc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qcjtbyhczc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qcjtbyhczc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#qcjtbyhczc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qcjtbyhczc .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#qcjtbyhczc .gt_left {
  text-align: left;
}

#qcjtbyhczc .gt_center {
  text-align: center;
}

#qcjtbyhczc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#qcjtbyhczc .gt_font_normal {
  font-weight: normal;
}

#qcjtbyhczc .gt_font_bold {
  font-weight: bold;
}

#qcjtbyhczc .gt_font_italic {
  font-style: italic;
}

#qcjtbyhczc .gt_super {
  font-size: 65%;
}

#qcjtbyhczc .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="qcjtbyhczc" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">term</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">estimate</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">std.error</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">statistic</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">p.value</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_group_heading_row">
      <td colspan="5" class="gt_group_heading">CLM</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">1|2</td>
      <td class="gt_row gt_right">&minus;1.34</td>
      <td class="gt_row gt_right">0.52</td>
      <td class="gt_row gt_right">&minus;2.60</td>
      <td class="gt_row gt_right">0.009</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">2|3</td>
      <td class="gt_row gt_right gt_striped">1.25</td>
      <td class="gt_row gt_right gt_striped">0.44</td>
      <td class="gt_row gt_right gt_striped">2.86</td>
      <td class="gt_row gt_right gt_striped">0.004</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">3|4</td>
      <td class="gt_row gt_right">3.47</td>
      <td class="gt_row gt_right">0.60</td>
      <td class="gt_row gt_right">5.80</td>
      <td class="gt_row gt_right"><0.001</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">4|5</td>
      <td class="gt_row gt_right gt_striped">5.01</td>
      <td class="gt_row gt_right gt_striped">0.73</td>
      <td class="gt_row gt_right gt_striped">6.85</td>
      <td class="gt_row gt_right gt_striped"><0.001</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">contactyes</td>
      <td class="gt_row gt_right">1.53</td>
      <td class="gt_row gt_right">0.48</td>
      <td class="gt_row gt_right">3.21</td>
      <td class="gt_row gt_right">0.001</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">tempwarm</td>
      <td class="gt_row gt_right gt_striped">2.50</td>
      <td class="gt_row gt_right gt_striped">0.53</td>
      <td class="gt_row gt_right gt_striped">4.73</td>
      <td class="gt_row gt_right gt_striped"><0.001</td>
    </tr>
    <tr class="gt_group_heading_row">
      <td colspan="5" class="gt_group_heading">CLMM</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">1|2</td>
      <td class="gt_row gt_right">&minus;1.62</td>
      <td class="gt_row gt_right">0.68</td>
      <td class="gt_row gt_right">&minus;2.38</td>
      <td class="gt_row gt_right">0.017</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">2|3</td>
      <td class="gt_row gt_right gt_striped">1.51</td>
      <td class="gt_row gt_right gt_striped">0.60</td>
      <td class="gt_row gt_right gt_striped">2.51</td>
      <td class="gt_row gt_right gt_striped">0.012</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">3|4</td>
      <td class="gt_row gt_right">4.23</td>
      <td class="gt_row gt_right">0.81</td>
      <td class="gt_row gt_right">5.23</td>
      <td class="gt_row gt_right"><0.001</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">4|5</td>
      <td class="gt_row gt_right gt_striped">6.09</td>
      <td class="gt_row gt_right gt_striped">0.97</td>
      <td class="gt_row gt_right gt_striped">6.26</td>
      <td class="gt_row gt_right gt_striped"><0.001</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">tempwarm</td>
      <td class="gt_row gt_right">3.06</td>
      <td class="gt_row gt_right">0.60</td>
      <td class="gt_row gt_right">5.14</td>
      <td class="gt_row gt_right"><0.001</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">contactyes</td>
      <td class="gt_row gt_right gt_striped">1.83</td>
      <td class="gt_row gt_right gt_striped">0.51</td>
      <td class="gt_row gt_right gt_striped">3.58</td>
      <td class="gt_row gt_right gt_striped"><0.001</td>
    </tr>
  </tbody>
  
  
</table></div>
<p>Both fixed effect estimates <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span> are higher in the CLMM.
Use <code>anova</code> to compare the CLMM to the CLM:</p>
<pre class="r"><code>anova(
  clm_rating_contact_temp, clmm_rating_contact_temp
)</code></pre>
<pre><code>## Likelihood ratio tests of cumulative link models:
##  
##                          formula:                              link: threshold:
## clm_rating_contact_temp  rating ~ contact + temp               logit flexible  
## clmm_rating_contact_temp rating ~ temp + contact + (1 | judge) logit flexible  
## 
##                          no.par    AIC  logLik LR.stat df Pr(&gt;Chisq)   
## clm_rating_contact_temp       6 184.98 -86.492                         
## clmm_rating_contact_temp      7 177.13 -81.565   9.853  1   0.001696 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Unsurprisingly, the <code>judge</code> term makes a significant improvement to the fit.
We can extract profile confidence intervals on the variance <span class="math inline">\(\sigma_u\)</span> using <code>stats::profile</code>:</p>
<pre class="r"><code>profile(clmm2_rating_contact_temp,
        range = c(0.1, 4), nSteps = 30, trace = 0) %&gt;%
  confint()</code></pre>
<pre><code>##           2.5 %  97.5 %
## stDev 0.5014584 2.26678</code></pre>
<p>Note that these intervals are asymmetric (<span class="math inline">\(\sigma_u\)</span> = 1.31), unlike the less accurate Wald tests.
We can produce “best guess” estimates for <code>judge</code> effects using <em>conditional modes</em>:</p>
<pre class="r"><code>tibble(
  judge_effect = clmm_rating_contact_temp$ranef,
  cond_var = clmm_rating_contact_temp$condVar
) %&gt;%
  mutate(
    judge = fct_reorder(factor(1:n()), judge_effect),
    conf.low = judge_effect - qnorm(0.975) * sqrt(cond_var),
    conf.high = judge_effect + qnorm(0.975) * sqrt(cond_var)
  ) %&gt;%
  ggp(aes(y = judge, x = judge_effect)) +
  geom_point() +
  geom_linerange(aes(xmin = conf.low, xmax = conf.high)) +
  cowplot::theme_minimal_vgrid()</code></pre>
<p><img src="/post/2020-03-10-learning-ordinal-regression-in-r_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<div id="predictions" class="section level4">
<h4>Predictions</h4>
<p>There are different ways to extract predicted probabilities.
First, and most obviously, with the <code>predict</code> function:</p>
<pre class="r"><code>wine %&gt;%
  bind_cols(
    pred =  predict(
      # Have to use clmm2 for predict
      clmm2_rating_contact_temp,
      newdata = wine
    )
  ) %&gt;%
  # These are predicted probabilities for the average judge, so we can
  #  exclude that variable
  distinct(rating, temp, contact, pred) %&gt;%
  arrange(temp, contact, rating)</code></pre>
<pre><code>## # A tibble: 15 x 4
##    rating temp  contact   pred
##    &lt;ord&gt;  &lt;fct&gt; &lt;fct&gt;    &lt;dbl&gt;
##  1 1      cold  no      0.165 
##  2 2      cold  no      0.655 
##  3 3      cold  no      0.166 
##  4 1      cold  yes     0.0305
##  5 2      cold  yes     0.390 
##  6 3      cold  yes     0.496 
##  7 4      cold  yes     0.0696
##  8 2      warm  no      0.166 
##  9 3      warm  no      0.587 
## 10 4      warm  no      0.191 
## 11 5      warm  no      0.0463
## 12 2      warm  yes     0.0313
## 13 3      warm  yes     0.306 
## 14 4      warm  yes     0.428 
## 15 5      warm  yes     0.233</code></pre>
<p>This only gives us predictions for <code>rating</code>, <code>temp</code> and <code>contact</code> values which exist in the data.
There is no <code>rating</code> &gt; 3 for <code>temp</code> cold and <code>contact</code> no, for example.
Another way is to pre-specify which values we want to predict:</p>
<pre class="r"><code>nd &lt;-
  crossing(
    temp = factor(c(&quot;cold&quot;, &quot;warm&quot;)),
    contact = factor(c(&quot;no&quot;, &quot;yes&quot;)),
    rating = factor(1:5, ordered = T)
  )
nd %&gt;%
  bind_cols(pred = predict(clmm2_rating_contact_temp, nd)) %&gt;%
  ggplot(aes(x = glue::glue(&quot;{temp}-{contact}&quot;), y = pred, fill = rating)) +
  geom_col() +
  cowplot::theme_minimal_hgrid() +
  scale_y_continuous(expand = c(0, 0), labels = scales::percent) +
  labs(x = &quot;temp-contact&quot;)</code></pre>
<p><img src="/post/2020-03-10-learning-ordinal-regression-in-r_files/figure-html/unnamed-chunk-24-1.png" width="480" /></p>
<p>We can also get model-estimated cumulative probabilities by considering the model coefficients.
For example, for a cold <code>temp</code> and <code>contact</code>, the cumulative probability of a bitterness <code>rating</code> <span class="math inline">\(j\)</span> or less:</p>
<p><span class="math display">\[
P(y_i \leq j) = \text{logit}^{-1} [\theta_j - \beta_2 \text{contact}_i]
\]</span></p>
<p>where we are considering the average judge (<span class="math inline">\(u(\text{judge}_i) = 0\)</span>).
The inverse logit is <span class="math inline">\(\text{logit}^{-1}(x) = 1 / (1 + \exp(x))\)</span>, and can be calculated with <code>plogis</code> as a shorthand.
We can subtract cumulative probabilites to get non-cumulative probabilities of a category <span class="math inline">\(j\)</span>, for example:</p>
<pre class="r"><code>plogis(clmm_rating_contact_temp$Theta[3] - clmm_rating_contact_temp$beta[2]) -
  plogis(clmm_rating_contact_temp$Theta[2] - clmm_rating_contact_temp$beta[2])</code></pre>
<pre><code>## contactyes 
##  0.4960357</code></pre>
<p>which matches the value calculated previously for <span class="math inline">\(j\)</span> = 3.</p>
</div>
<div id="choice-of-link-function" class="section level4">
<h4>Choice of link function</h4>
<p>So far, we have used the logit link (and briefly the probit link to compare to linear regression).
The links available to <code>ordinal::clmm</code> are logit, probit, cloglog, loglog, and cauchit.</p>
<p>We can fit the CLMM using all of these links and compare log-likelihoods:</p>
<pre class="r"><code>wine %&gt;%
  nest(everything()) %&gt;%
  crossing(
    link = c(&quot;logit&quot;, &quot;probit&quot;, &quot;cloglog&quot;, &quot;loglog&quot;, &quot;cauchit&quot;)
  ) %&gt;%
  mutate(
    mod = map2(
      data, link,
      ~clmm(
        rating ~ 1 + contact + temp + (1|judge),
        data = .x, link = .y
      )
    )
  ) %&gt;%
  mutate(
    mod_glance = map(mod, glance)
  ) %&gt;%
  unnest(mod_glance) %&gt;%
  select(link, logLik, AIC, BIC) %&gt;%
  arrange(logLik)</code></pre>
<pre><code>## # A tibble: 5 x 4
##   link    logLik   AIC   BIC
##   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 cauchit  -86.8  188.  204.
## 2 cloglog  -82.7  179.  195.
## 3 logit    -81.6  177.  193.
## 4 loglog   -81.5  177.  193.
## 5 probit   -80.9  176.  192.</code></pre>
<p>The probit model appears to be the best description of the data.</p>
<p>We can also consider the effect of “flexible” vs “equidistant” thresholds:</p>
<pre class="r"><code>wine %&gt;%
  nest(everything()) %&gt;%
  crossing(
    link = c(&quot;logit&quot;, &quot;probit&quot;, &quot;cloglog&quot;, &quot;loglog&quot;, &quot;cauchit&quot;),
    threshold = c(&quot;flexible&quot;, &quot;equidistant&quot;)
  ) %&gt;%
  mutate(
    mod = pmap(
      list(data, link, threshold),
      function(a, b, c) {
        clmm(
          rating ~ 1 + contact + temp + (1|judge),
          data = a, link = b, threshold = c
        )
      }
    )
  ) %&gt;%
  mutate(
    mod_glance = map(mod, glance)
  ) %&gt;%
  unnest(mod_glance) %&gt;%
  select(link, threshold, logLik, edf, AIC, BIC) %&gt;%
  arrange(logLik)</code></pre>
<pre><code>## # A tibble: 10 x 6
##    link    threshold   logLik   edf   AIC   BIC
##    &lt;chr&gt;   &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 cauchit equidistant  -87.8     5  186.  197.
##  2 cauchit flexible     -86.8     7  188.  204.
##  3 loglog  equidistant  -84.4     5  179.  190.
##  4 cloglog equidistant  -83.3     5  177.  188.
##  5 logit   equidistant  -83.1     5  176.  187.
##  6 cloglog flexible     -82.7     7  179.  195.
##  7 probit  equidistant  -82.5     5  175.  186.
##  8 logit   flexible     -81.6     7  177.  193.
##  9 loglog  flexible     -81.5     7  177.  193.
## 10 probit  flexible     -80.9     7  176.  192.</code></pre>
<p>Note the change in degrees of freedom, resulting in the equidistant probit model having the lowest BIC.
In terms of log likelihood, however, flexible always outperform equidistant thresholds.</p>
</div>
</div>
</div>
<div id="bayesian-regression" class="section level2">
<h2>Bayesian regression</h2>
<p>Load the <code>brms</code> package:</p>
<pre class="r"><code>library(brms)
# Detect and set the number of cores
options(mc.cores = parallel::detectCores())</code></pre>
<p>We will fit a null cumulative link mixed model, and models with the fixed effects with default priors:</p>
<pre class="r"><code>f_rating_null &lt;- rating ~ 1 + (1|judge)
f_rating_contact &lt;- rating ~ 1 + contact + (1|judge)
f_rating_contact_temp &lt;- rating ~ 1 + contact + temp + (1|judge)
get_prior(f_rating_contact_temp, data = wine, family = cumulative(&quot;logit&quot;))</code></pre>
<pre><code>##                  prior     class       coef group resp dpar nlpar bound
## 1                              b                                       
## 2                              b contactyes                            
## 3                              b   tempwarm                            
## 4  student_t(3, 0, 10) Intercept                                       
## 5                      Intercept          1                            
## 6                      Intercept          2                            
## 7                      Intercept          3                            
## 8                      Intercept          4                            
## 9  student_t(3, 0, 10)        sd                                       
## 10                            sd            judge                      
## 11                            sd  Intercept judge</code></pre>
<p>First, the null model with no predictors:</p>
<pre class="r"><code>brm_rating_null &lt;-
  brm(
    f_rating_null,
    data = wine,
    family = cumulative(&quot;logit&quot;),
    sample_prior = TRUE,
    file = here(&quot;data&quot;, &quot;ordinal_regression&quot;, &quot;brm_rating_null.rds&quot;)
  )</code></pre>
<p>We can visualize the two priors (on thresholds/Intercepts, and on SD of judge effects) with <code>brms:prior_samples</code>:</p>
<pre class="r"><code>get_prior(f_rating_null, data = wine, family = cumulative(&quot;logit&quot;))</code></pre>
<pre><code>##                 prior     class      coef group resp dpar nlpar bound
## 1 student_t(3, 0, 10) Intercept                                      
## 2                     Intercept         1                            
## 3                     Intercept         2                            
## 4                     Intercept         3                            
## 5                     Intercept         4                            
## 6 student_t(3, 0, 10)        sd                                      
## 7                            sd           judge                      
## 8                            sd Intercept judge</code></pre>
<pre class="r"><code>p1 &lt;-
  prior_samples(brm_rating_null) %&gt;%
  gather(term, value) %&gt;%
  ggp(aes(x = value)) +
  geom_density(size = 1) +
  geom_density(
    data = tibble(x = rstudent_t(n = 4000, df = 3, mu = 0, sigma = 10),
                  prior = &quot;student_t(3, 0, 10)&quot;, term = &quot;Intercept&quot;),
    aes(x, color = prior), size = 1
  ) +
  geom_density(
    data = tibble(x = rstudent_t(n = 4000, df = 3, mu = 0, sigma = 10),
                  prior = &quot;abs(student_t(3, 0, 10))&quot;, term = &quot;sd_judge&quot;),
    aes(abs(x), color = prior), size = 1,
  ) +
  facet_wrap(~term, scales = &quot;free&quot;) +
  cowplot::theme_minimal_vgrid() +
  theme(axis.text.y = element_blank())
p1 +
  (p1 + coord_cartesian(xlim = c(-10, 20))) +
  plot_layout(ncol = 1, guides = &quot;collect&quot;)</code></pre>
<p><img src="/post/2020-03-10-learning-ordinal-regression-in-r_files/figure-html/unnamed-chunk-32-1.png" width="480" /></p>
<p>Note that, since a standard deviation can’t be negative, <code>brms</code> automatically takes the absolute value of the defualt <code>student_t(3, 0, 10)</code> prior.</p>
<p>These are obviously very uninformative priors.
For instance, Intercepts (aka thresholds <span class="math inline">\(\theta_j\)</span>) between -20 and +20 correspond to the following probabilities:</p>
<pre class="r"><code>tibble(theta = seq(-20, 20)) %&gt;%
  mutate(p = inv_logit_scaled(theta)) %&gt;%
  ggp(aes(x = theta, y = p)) +
  geom_line(size = 1)</code></pre>
<p><img src="/post/2020-03-10-learning-ordinal-regression-in-r_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>So any prior values of, say, -10 are assigning essentially zero cumulative probability for a level <span class="math inline">\(\leq j\)</span>.</p>
<p>Now that we’ve thought about our (default) prior assumptions, investigate the chains:</p>
<pre class="r"><code>plot(brm_rating_null)</code></pre>
<p><img src="/post/2020-03-10-learning-ordinal-regression-in-r_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>The Intercept trace plots look good to me.
There are some spikes in <code>sd_judge__Intercept</code>, but not enough to be concerning.</p>
<p>Print the model estimates:</p>
<pre class="r"><code>brm_rating_null</code></pre>
<pre><code>##  Family: cumulative 
##   Links: mu = logit; disc = identity 
## Formula: rating ~ 1 + (1 | judge) 
##    Data: wine (Number of observations: 72) 
## Samples: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
##          total post-warmup samples = 4000
## 
## Group-Level Effects: 
## ~judge (Number of levels: 9) 
##               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sd(Intercept)     0.83      0.47     0.09     1.90 1.00     1100     1213
## 
## Population-Level Effects: 
##              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept[1]    -2.88      0.60    -4.13    -1.81 1.00     1704     2153
## Intercept[2]    -0.55      0.40    -1.37     0.26 1.00     2201     2754
## Intercept[3]     1.16      0.43     0.35     2.09 1.00     2249     2615
## Intercept[4]     2.53      0.54     1.57     3.70 1.00     2396     2959
## 
## Samples were drawn using sampling(NUTS). For each parameter, Eff.Sample 
## is a crude measure of effective sample size, and Rhat is the potential 
## scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
<p>The <code>Rhat</code> values are also a good sign of model convergence.
Compare our null Bayesian model estimates to the frequentist estimates:</p>
<pre class="r"><code># Can&#39;t figure out how to extract random effect SDs from a clmm model, use clmm2
clmm2_rating_null &lt;-
  clmm2(
    rating ~ 1, random = judge,
    data = wine, link = &quot;logistic&quot;, Hess = TRUE
  )
# Unfortunately, clmm2 doesn&#39;t have a broom::tidy() function
summary(clmm2_rating_null) %&gt;%
  coef() %&gt;%
  as_tibble() %&gt;%
  mutate(term = str_c(&quot;b_Intercept[&quot;, 1:4, &quot;]&quot;)) %&gt;%
  bind_rows(
    tibble(
      Estimate = as.numeric(clmm2_rating_null$stDev),
      term = &quot;sd_judge__Intercept&quot;
    )
  ) %&gt;%
  janitor::clean_names() %&gt;%
  left_join(
    tidy(brm_rating_null),
    by = &quot;term&quot;
  ) %&gt;%
  select(term, everything()) %&gt;%
  mutate(
    pr_z = scales::pvalue(pr_z),
    across(is.numeric, ~round(., 2))
  ) %&gt;%
  gt() %&gt;%
  tab_spanner(
    label = &quot;ordinal::clmm&quot;,
    columns = vars(estimate.x, std_error, z_value, pr_z)
  ) %&gt;%
  tab_spanner(
    label = &quot;brms::brm&quot;,
    columns = vars(estimate.y, std.error, lower, upper)
  )</code></pre>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#mybjnzprat .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
}

#mybjnzprat .gt_heading {
  background-color: #FFFFFF;
  border-bottom-color: #FFFFFF;
  border-left-style: hidden;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: hidden;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mybjnzprat .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#mybjnzprat .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#mybjnzprat .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mybjnzprat .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mybjnzprat .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#mybjnzprat .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#mybjnzprat .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#mybjnzprat .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#mybjnzprat .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#mybjnzprat .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#mybjnzprat .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#mybjnzprat .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#mybjnzprat .gt_from_md > :first-child {
  margin-top: 0;
}

#mybjnzprat .gt_from_md > :last-child {
  margin-bottom: 0;
}

#mybjnzprat .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#mybjnzprat .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#mybjnzprat .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mybjnzprat .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#mybjnzprat .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mybjnzprat .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#mybjnzprat .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mybjnzprat .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mybjnzprat .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#mybjnzprat .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mybjnzprat .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#mybjnzprat .gt_left {
  text-align: left;
}

#mybjnzprat .gt_center {
  text-align: center;
}

#mybjnzprat .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#mybjnzprat .gt_font_normal {
  font-weight: normal;
}

#mybjnzprat .gt_font_bold {
  font-weight: bold;
}

#mybjnzprat .gt_font_italic {
  font-style: italic;
}

#mybjnzprat .gt_super {
  font-size: 65%;
}

#mybjnzprat .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="mybjnzprat" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_center gt_columns_bottom_border" rowspan="2" colspan="1">term</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="4">
        <span class="gt_column_spanner">ordinal::clmm</span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="4">
        <span class="gt_column_spanner">brms::brm</span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">estimate.x</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">std_error</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">z_value</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">pr_z</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">estimate.y</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">std.error</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">lower</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">upper</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left">b_Intercept[1]</td>
      <td class="gt_row gt_right">-2.72</td>
      <td class="gt_row gt_right">0.52</td>
      <td class="gt_row gt_right">-5.25</td>
      <td class="gt_row gt_left">&lt;0.001</td>
      <td class="gt_row gt_right">-2.88</td>
      <td class="gt_row gt_right">0.60</td>
      <td class="gt_row gt_right">-3.91</td>
      <td class="gt_row gt_right">-1.95</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">b_Intercept[2]</td>
      <td class="gt_row gt_right gt_striped">-0.54</td>
      <td class="gt_row gt_right gt_striped">0.32</td>
      <td class="gt_row gt_right gt_striped">-1.72</td>
      <td class="gt_row gt_left gt_striped">0.085</td>
      <td class="gt_row gt_right gt_striped">-0.55</td>
      <td class="gt_row gt_right gt_striped">0.40</td>
      <td class="gt_row gt_right gt_striped">-1.21</td>
      <td class="gt_row gt_right gt_striped">0.11</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">b_Intercept[3]</td>
      <td class="gt_row gt_right">1.10</td>
      <td class="gt_row gt_right">0.34</td>
      <td class="gt_row gt_right">3.24</td>
      <td class="gt_row gt_left">0.001</td>
      <td class="gt_row gt_right">1.16</td>
      <td class="gt_row gt_right">0.43</td>
      <td class="gt_row gt_right">0.50</td>
      <td class="gt_row gt_right">1.89</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped">b_Intercept[4]</td>
      <td class="gt_row gt_right gt_striped">2.35</td>
      <td class="gt_row gt_right gt_striped">0.46</td>
      <td class="gt_row gt_right gt_striped">5.13</td>
      <td class="gt_row gt_left gt_striped">&lt;0.001</td>
      <td class="gt_row gt_right gt_striped">2.53</td>
      <td class="gt_row gt_right gt_striped">0.54</td>
      <td class="gt_row gt_right gt_striped">1.74</td>
      <td class="gt_row gt_right gt_striped">3.45</td>
    </tr>
    <tr>
      <td class="gt_row gt_left">sd_judge__Intercept</td>
      <td class="gt_row gt_right">0.57</td>
      <td class="gt_row gt_right">NA</td>
      <td class="gt_row gt_right">NA</td>
      <td class="gt_row gt_left">NA</td>
      <td class="gt_row gt_right">0.83</td>
      <td class="gt_row gt_right">0.47</td>
      <td class="gt_row gt_right">0.16</td>
      <td class="gt_row gt_right">1.69</td>
    </tr>
  </tbody>
  
  
</table></div>
<p>Estimates are pretty close, even with our naive priors.</p>
<p>So what are reasonable priors for this kind of analysis?
My go-to resource for this kind of thing is <a href="https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations">this page from the stan wiki</a>, but under the “Prior for cutpoints in ordered logit or probit regression”, they say “Need to flesh out this section with examples.”</p>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references hanging-indent">
<div id="ref-Randall1989">
<p>Randall, J. 1989. “The Analysis of Sensory Data by Generalised Linear Model.” <em>Biometrical Journal</em> 7: 781–93.</p>
</div>
</div>
</div>
